[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn EuroTrip.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120"