# Generated by Django 5.1.1 on 2024-11-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
