# Generated by Django 5.1.1 on 2024-11-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_pago_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_llegada',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_salida',
            field=models.CharField(max_length=100),
        ),
    ]
